"""
项目配置文件
"""

import os

# 环境检测
IS_PRODUCTION = os.environ.get("ENVIRONMENT", "development") == "production"
GPU_COUNT = int(os.environ.get("GPU_COUNT", "1"))  # 默认为1，可通过环境变量设置

# 模型配置
TEACHER_MODEL_ID = "Valdemardi/DeepSeek-R1-Distill-Llama-70B-AWQ"  # 教师模型
STUDENT_MODEL_ID = "Qwen/Qwen1.5-14B-Chat"  # 学生模型
OUTPUT_DIR = "/mnt/data/model_outputs" if IS_PRODUCTION else "./output"  # 输出目录

# 数据集配置
DATASET_ID = "liucong/Chinese-DeepSeek-R1-Distill-data-110k-SFT"  # 数据集ID
PROCESSED_DATA_DIR = "/mnt/data/processed_data" if IS_PRODUCTION else "./data/processed"  # 处理后的数据目录
CACHE_DIR = "/mnt/data/model_cache" if IS_PRODUCTION else "./cache"  # 缓存目录

# 3090x4 GPU环境参数配置
GPU3090_4X_BATCH_SIZE = 2  # 每张卡的batch size
GPU3090_4X_GRADIENT_ACCUMULATION_STEPS = 16  # 梯度累积步数，提高有效批量大小
GPU3090_4X_LEARNING_RATE = 1e-5  # 适合LoRA微调的学习率
GPU3090_4X_NUM_TRAIN_EPOCHS = 1  # 一个epoch通常已足够
GPU3090_4X_WARMUP_RATIO = 0.03  # 热身比例
GPU3090_4X_MAX_SOURCE_LENGTH = 1024  # 输入序列长度
GPU3090_4X_MAX_TARGET_LENGTH = 1536  # 输出序列长度
GPU3090_4X_VAL_SET_SIZE = 3000  # 验证集大小
GPU3090_4X_LOGGING_STEPS = 20  # 日志记录步数
GPU3090_4X_SAVE_STEPS = 500  # 模型保存步数
GPU3090_4X_LORA_R = 16  # LoRA rank
GPU3090_4X_LORA_ALPHA = 32  # LoRA alpha系数
GPU3090_4X_LORA_DROPOUT = 0.1  # LoRA dropout

# 开发环境训练配置
DEV_BATCH_SIZE = 4
DEV_GRADIENT_ACCUMULATION_STEPS = 4
DEV_LEARNING_RATE = 2e-5
DEV_NUM_TRAIN_EPOCHS = 3
DEV_WARMUP_RATIO = 0.1
DEV_MAX_SOURCE_LENGTH = 512
DEV_MAX_TARGET_LENGTH = 1024
DEV_VAL_SET_SIZE = 2000
DEV_LOGGING_STEPS = 10

# 生产环境训练配置
PROD_BATCH_SIZE = 8
PROD_GRADIENT_ACCUMULATION_STEPS = 8
PROD_LEARNING_RATE = 1e-5
PROD_NUM_TRAIN_EPOCHS = 1
PROD_WARMUP_RATIO = 0.03
PROD_MAX_SOURCE_LENGTH = 1024
PROD_MAX_TARGET_LENGTH = 2048
PROD_VAL_SET_SIZE = 5000
PROD_LOGGING_STEPS = 50

# 根据环境和GPU数量选择配置
if GPU_COUNT == 4 and os.environ.get("GPU_TYPE", "") == "3090":
    # 使用3090x4专用配置
    BATCH_SIZE = GPU3090_4X_BATCH_SIZE
    GRADIENT_ACCUMULATION_STEPS = GPU3090_4X_GRADIENT_ACCUMULATION_STEPS
    LEARNING_RATE = GPU3090_4X_LEARNING_RATE
    NUM_TRAIN_EPOCHS = GPU3090_4X_NUM_TRAIN_EPOCHS
    WARMUP_RATIO = GPU3090_4X_WARMUP_RATIO
    MAX_SOURCE_LENGTH = GPU3090_4X_MAX_SOURCE_LENGTH
    MAX_TARGET_LENGTH = GPU3090_4X_MAX_TARGET_LENGTH
    VAL_SET_SIZE = GPU3090_4X_VAL_SET_SIZE
    LOGGING_STEPS = GPU3090_4X_LOGGING_STEPS
    LORA_R = GPU3090_4X_LORA_R
    LORA_ALPHA = GPU3090_4X_LORA_ALPHA
    LORA_DROPOUT = GPU3090_4X_LORA_DROPOUT
else:
    # 使用默认开发或生产环境配置
    BATCH_SIZE = PROD_BATCH_SIZE if IS_PRODUCTION else DEV_BATCH_SIZE
    GRADIENT_ACCUMULATION_STEPS = PROD_GRADIENT_ACCUMULATION_STEPS if IS_PRODUCTION else DEV_GRADIENT_ACCUMULATION_STEPS
    LEARNING_RATE = PROD_LEARNING_RATE if IS_PRODUCTION else DEV_LEARNING_RATE
    NUM_TRAIN_EPOCHS = PROD_NUM_TRAIN_EPOCHS if IS_PRODUCTION else DEV_NUM_TRAIN_EPOCHS
    WARMUP_RATIO = PROD_WARMUP_RATIO if IS_PRODUCTION else DEV_WARMUP_RATIO
    MAX_SOURCE_LENGTH = PROD_MAX_SOURCE_LENGTH if IS_PRODUCTION else DEV_MAX_SOURCE_LENGTH
    MAX_TARGET_LENGTH = PROD_MAX_TARGET_LENGTH if IS_PRODUCTION else DEV_MAX_TARGET_LENGTH
    VAL_SET_SIZE = PROD_VAL_SET_SIZE if IS_PRODUCTION else DEV_VAL_SET_SIZE
    LOGGING_STEPS = PROD_LOGGING_STEPS if IS_PRODUCTION else DEV_LOGGING_STEPS

# 开发环境LoRA配置
DEV_LORA_R = 8
DEV_LORA_ALPHA = 16
DEV_LORA_DROPOUT = 0.05
DEV_TARGET_MODULES = ["q_proj", "k_proj", "v_proj", "o_proj"]

# 生产环境LoRA配置
PROD_LORA_R = 16
PROD_LORA_ALPHA = 32
PROD_LORA_DROPOUT = 0.1
PROD_TARGET_MODULES = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]

# LoRA配置
USE_LORA = True  # 是否使用LoRA
LORA_R = LORA_R if 'LORA_R' in locals() else (PROD_LORA_R if IS_PRODUCTION else DEV_LORA_R)
LORA_ALPHA = LORA_ALPHA if 'LORA_ALPHA' in locals() else (PROD_LORA_ALPHA if IS_PRODUCTION else DEV_LORA_ALPHA)
LORA_DROPOUT = LORA_DROPOUT if 'LORA_DROPOUT' in locals() else (PROD_LORA_DROPOUT if IS_PRODUCTION else DEV_LORA_DROPOUT)
TARGET_MODULES = PROD_TARGET_MODULES if IS_PRODUCTION else DEV_TARGET_MODULES

# 推理参数
INFERENCE_TEMPERATURE = 0.7
INFERENCE_TOP_P = 0.9
MAX_NEW_TOKENS = 2048 if IS_PRODUCTION else 1024
DO_SAMPLE = True

# 思考标记
THINK_START_TOKEN = "<think>"
THINK_END_TOKEN = "</think>"

# 特殊标记
CODE_RUN_TOKEN = "'''RUN"